### ISSUE TITLE
done

### ISSUE THREAD

**Issue by SDS1234** [zImPinguin/Bump-Bot#1]
Hallo,
Ich verstehe nicht genau was der bot macht, könnten Sie mir das erläutern?

Mit freundlichen Grüßen

**Comment by pinguulein** [comment]
Hi,

Mit diesem Bot kannstdu Server Bumpen dieser schaltet dann werbung auf den anderen Servern. 
Solltest du hilfe benötigen kannst du mich einfach anschreiben.

Mit freundlichen Grüßen
pingulein

**Comment by SDS1234** [comment]
Okay, herzlichen Dank für die schnelle Antwort 👍
